# Generated by Django 4.1.3 on 2023-05-27 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('reg_id', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(max_length=70)),
                ('lname', models.CharField(max_length=70)),
                ('username', models.CharField(max_length=70)),
                ('email', models.CharField(max_length=70)),
                ('passwd', models.CharField(max_length=40)),
                ('phone', models.IntegerField(default=0)),
                ('dob', models.CharField(max_length=70)),
                ('gender', models.CharField(max_length=70)),
            ],
        ),
    ]
