# Generated by Django 4.1.3 on 2023-05-27 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0002_myexpense'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mybudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('category', models.CharField(max_length=200)),
                ('date', models.CharField(max_length=200)),
                ('amount', models.CharField(max_length=200)),
            ],
        ),
    ]
