# Generated by Django 4.1.3 on 2023-05-28 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0004_alter_myexpense_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='mybudget',
            name='remain_amount',
            field=models.CharField(default='0', max_length=200),
        ),
    ]
