# Generated by Django 4.1.3 on 2023-05-28 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expense_tracker', '0005_mybudget_remain_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('date', models.CharField(max_length=200)),
                ('notify', models.CharField(max_length=400)),
            ],
        ),
        migrations.AlterField(
            model_name='mybudget',
            name='remain_amount',
            field=models.CharField(default='1000', max_length=200),
        ),
    ]
